[project]
name = "stocktracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.1",
    "plotly>=6.3.0",
    "pyarrow>=21.0.0",
    "streamlit>=1.48.1",
    "yfinance>=0.2.65",
]
